name: flutter_clean_architecture
description: "A Flutter application implementing clean architecture with riverpod for state management, and featuring theme and language switching capabilities."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  material_color_utilities: ^0.8.0
  dio: ^5.4.1
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  sqlite3: ^2.4.0
  web_socket_channel: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.16.0
  analyzer: ^6.4.1
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

scripts:
  gen_l10n: flutter gen-l10n
  build_runner_watch: flutter  pub run build_runner watch --delete-conflicting-outputs
  build_runner_build: flutter  pub run build_runner build --delete-conflicting-outputs